version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock  # Add this line
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock